# Netlify 설정 파일

[build]
  # 빌드 명령 (정적 사이트이므로 빌드 불필요)
  command = "echo 'No build required'"
  # 배포할 폴더 (루트 디렉토리)
  publish = "."
  # Functions 폴더
  functions = "netlify/functions"

# Redirects 설정 (SPA 라우팅 지원)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["admin"]}

# CORS 헤더 설정 (추가 보안)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
